# Generated by Django 3.2 on 2022-05-29 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220528_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='uuid',
        ),
    ]
